# Generated by Django 6.1 on 2026-09-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Message',
        ),
    ]
