# Generated by Django 6.0.7 on 2026-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='room_name',
            field=models.CharField(default='general', max_length=200),
        ),
    ]
