# Generated by Django 6.0.7 on 2026-08-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
